<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View Candidate Btn</name>
   <tag></tag>
   <elementGuidId>437e36b5-e7f8-4483-a95d-ced67aecdb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[@class=&quot;ant-table-tbody&quot;]/tr[1][@data-row-key=&quot;0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-table-row ant-table-row-level-0</value>
      <webElementGuid>5941b077-e5e2-476f-8a88-03d505c6bb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d5d7237-3539-402d-b699-9a8f89edfba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[@class=&quot;ant-table-tbody&quot;]/tr[1][@data-row-key=&quot;0&quot;]</value>
      <webElementGuid>98ba27c2-0ff4-465d-828d-342d2319b03e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
