<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Password Btn</name>
   <tag></tag>
   <elementGuidId>ac977d37-4d79-4588-bf12-fab15abf19cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()=&quot;PASSWORD&quot;]/parent::b/parent::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb4a316f-99b4-4e26-ad2a-26c402790a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()=&quot;PASSWORD&quot;]/parent::b/parent::a</value>
      <webElementGuid>386a5474-d0c8-4a46-94a3-d0b4b35e3d95</webElementGuid>
   </webElementProperties>
</WebElementEntity>
