<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Question 6 Checkbox</name>
   <tag></tag>
   <elementGuidId>a49f8be1-bd28-4955-b9bf-44239b2bc949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;43a8a3b5_a6e8_e811_a591_109836a5ea9c&quot;]//input[@value=&quot;No&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;43a8a3b5_a6e8_e811_a591_109836a5ea9c&quot;]//input[@value=&quot;No&quot;]</value>
      <webElementGuid>21507e17-e879-4437-8ccb-0bd64881e0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66b06a03-95b1-4e89-9263-a38047785e98</webElementGuid>
   </webElementProperties>
</WebElementEntity>
