<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Countries Link</name>
   <tag></tag>
   <elementGuidId>87e6d2fc-d428-4451-885e-50459f227543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[text()='countries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8f96a69-36b8-4347-b5d2-2b2533919a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[text()='countries']</value>
      <webElementGuid>75ee27c1-5669-41e3-97c6-bd35c96e0f5a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
