<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Head Office Address Btn</name>
   <tag></tag>
   <elementGuidId>5ec146a1-dcc6-4e55-8f7e-6a928140dd68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'robot-btn-editHeadOfficeAddress' and (text() = 'Edit' or . = 'Edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f620b012-18c7-4cb1-9f17-e0e9c0e6d743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>robot-btn-editHeadOfficeAddress</value>
      <webElementGuid>6633783d-8714-4580-b433-bf0f94d4ed15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>46374d61-3940-4ae5-bea8-d3c72fe6f059</webElementGuid>
   </webElementProperties>
</WebElementEntity>
