<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Question 6 Checkbox</name>
   <tag></tag>
   <elementGuidId>803f69d9-6698-48bf-b5dc-3f98c6d8f45f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;26be89ba_a5e8_e811_a591_109836a5ea9c&quot;]//input[@value=&quot;Yes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;26be89ba_a5e8_e811_a591_109836a5ea9c&quot;]//input[@value=&quot;Yes&quot;]</value>
      <webElementGuid>36f236de-f3d8-45a9-b482-2bad9072f46d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98efbfef-05ab-47e6-926f-4ccac86aa0d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
