<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Question 3 Checkbox</name>
   <tag></tag>
   <elementGuidId>cca46057-d46c-4e8e-b61a-0410de099cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;fc08de5c_415b_4a4d_a889_fca362df9cba&quot;]/label[1]/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;fc08de5c_415b_4a4d_a889_fca362df9cba&quot;]/label[1]/span[1]/input</value>
      <webElementGuid>4c4f1012-5031-4ca3-b9be-fedd4778cbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>385fcc32-4131-4e3f-87c5-0b2910e8efd0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
