<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Engagements Title Txt</name>
   <tag></tag>
   <elementGuidId>c4b1ecb1-425f-49fd-972a-aeb060f4d81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Engagements' or . = 'Engagements') and @class = 'engagement-board-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>265e3e50-c20b-4378-88fd-460a4b9b1ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engagements</value>
      <webElementGuid>d5b196ac-b9eb-4dd3-8ffc-248647e90e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>engagement-board-title</value>
      <webElementGuid>6a07ae36-dee1-4074-a826-c5477c83e053</webElementGuid>
   </webElementProperties>
</WebElementEntity>
