<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Engagement Notif View Now Btn</name>
   <tag></tag>
   <elementGuidId>9f822670-e09e-4e03-a209-a22e5fd46d73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[1]/td[4]/span[text()='Engagement']/parent::td//following-sibling::td[@class=&quot;actionTd&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5f7ea15-48f9-40e8-a5ef-b304b8c82ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[1]/td[4]/span[text()='Engagement']/parent::td//following-sibling::td[@class=&quot;actionTd&quot;]//button</value>
      <webElementGuid>494035f0-a81c-4510-a7c1-1bcb6484ff35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
