<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Keyword Suggestion</name>
   <tag></tag>
   <elementGuidId>2e23c3a0-1f2b-4146-ae04-7eeec13f757a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>95f4f236-2466-4034-9d4f-6118a550a880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>electrical engineer</value>
      <webElementGuid>a7ab1609-248b-49aa-bb65-ea055a2acdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div/ul/li</value>
      <webElementGuid>5c1e4489-7e5e-4192-a207-0d423f8c6af3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
