<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Country Btn</name>
   <tag></tag>
   <elementGuidId>10dd66f0-a42b-4eab-828b-87638185bf85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#country > div.ant-select-selection.ant-select-selection--single</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='country']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>779e117f-631a-4c04-a67f-69c7b1c3d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection
            ant-select-selection--single</value>
      <webElementGuid>cc8e51ee-b073-4402-8e7a-0bcac2611f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>617d3dac-bfe9-4176-8f89-a271d84eb5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>e1c21056-d02b-47ec-8519-d7f18cf3ab92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>59580487-f8fb-402b-910b-229472cfec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f08fd567-ec6a-4e1b-be3d-047b387f7058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__meta</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>dc7b7ed7-5e51-46f0-8f9e-c654af364044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-__field</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d141bf18-d545-4467-81cc-78f2ad8963ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c40da678-bc18-4ac5-819e-901f90a57702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Country </value>
      <webElementGuid>76922015-2f3d-4c98-8af2-d97df98c4e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[1]/div[@class=&quot;ant-modal-wrap&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ubidy-ui form-address&quot;]/div[@class=&quot;gutter-example&quot;]/div[@class=&quot;ant-row-flex ant-row-flex-start&quot;]/div[@class=&quot;ant-col-24 gutter-row&quot;]/div[@class=&quot;gutter-box&quot;]/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;ant-row ant-form-item form_md&quot;]/div[@class=&quot;ant-col-14 ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control&quot;]/span[@class=&quot;ant-form-item-children&quot;]/div[@id=&quot;country&quot;]/div[@class=&quot;ant-select-selection
            ant-select-selection--single&quot;]</value>
      <webElementGuid>76020f31-d91e-4e41-82b4-f10907e0f4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='country']/div</value>
      <webElementGuid>19410f82-bde8-4b5f-993e-97edc7dd0097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/span/div/div</value>
      <webElementGuid>b0583f99-0ea9-4903-bfa1-d5dca2760aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Country ' or . = 'Select Country ')]</value>
      <webElementGuid>82728fea-dd93-4c21-afc8-3ad5a6ee00a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
