<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sidebar Company Logo</name>
   <tag></tag>
   <elementGuidId>87206b2c-2429-494f-b2d4-e6ed7be3ddba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@class='MainSidebar-section']//div[@class='avatar-wrapper']//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5bc4eb1a-9691-4d39-908d-70589bc8bdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@class='MainSidebar-section']//div[@class='avatar-wrapper']//a[1]</value>
      <webElementGuid>f8b945fc-2671-4d12-b0a7-e0f7628e5611</webElementGuid>
   </webElementProperties>
</WebElementEntity>
